[package]
name = "els"
version = "0.0.1"
edition = "2021"
description = "An Erg compiler frontend for IDEs, implements LSP."
authors = ["Shunsuke Shibayama <sbym1346@gmail.com>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erg_common = { git = "http://github.com/erg-lang/erg", branch = "main" }
erg_type = { git = "https://github.com/erg-lang/erg", branch = "main" }
erg_compiler = { git = "https://github.com/erg-lang/erg", branch = "main" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.85"
lsp-types = "0.93.1"
url = "2.3.1"
urlencoding = "2.1.2"
